{
    {
        type = "Rectangle",
        px = "0.5",
        py = "0.5",
        sw = "0.7",
        sh = "0.7",
        color = "#557744",
        children = {},
    },
    {
        type = "Ellipse",
        px = "0.5",
        py = "0.5",
        sw = "0.5",
        sh = "0.6",
        color = "#227733",
        children = {},
    },
    {
        type = "Polygon",
        px = "0.5",
        py = "0.5",
        sw = "0",
        sh = "0",
        color = "#5577ff",
        points = {
            0,
            -100,
            100,
            0,
            50,
            100,
            -50,
            100,
            -100,
            0,
        },
        children = {},
    },
    {
        type = "Line",
        px = "0.5",
        py = "0.5",
        sw = "0",
        sh = "0",
        color = "#ffaa00",
        points = {
            0,
            -50,
            50,
            0,
            25,
            50,
            -25,
            50,
            -50,
            0,
        },
        children = {},
    },
    {
        type = "Point",
        px = "0.5",
        py = "0.5",
        sw = "0",
        sh = "0",
        color = "#ff00ff",
        points = {
            0,
            0,
            -25,
            -25,
        },
        children = {},
    },
    {
        type = "Button",
        id = "btnTest",
        px = "0.5",
        py = "0.7",
        sw = 150,
        sh = 50,
        icon = "media/edit.png",
        text = "YES",
        color = "#ffaa77",
        children = {},
    },
    {
        type = "Input",
        id = "inputTest",
        px = "0.5",
        py = "0.3",
        sw = 150,
        sh = 50,
        color = "#111111aa",
        children = {},
    },
    {
        type = "Video",
        id = "idVideo",
        px = "0.5",
        py = "0.5",
        sw = "0.3",
        sh = "0.3",
        path = "media/movie.ogg",
        children = {},
    },
    {
        type = "Particle",
        px = "0.5",
        py = "0.5",
        sw = "0.5",
        sh = "0.5",
        path = "media/preview.png",
        children = {},
    },
    {
        type = "Text",
        px = "0.5",
        py = "0.5",
        sw = "0",
        sh = "0",
        text = "TEXT...",
        color = "#ff0000",
        children = {},
    },
    {
        type = "Button",
        id = "idButton",
        px = 50,
        py = 50,
        sw = 25,
        sh = 25,
        icon = "media/folder.png",
        children = {},
    },
    {
        type = "Check",
        id = "nodeLayer",
        px = "0.7",
        py = "0.5",
        sw = "100",
        sh = "100",
        color = "#ff0aff",
        children = {},
    },
}