{
    {
        type = "Rectangle",
        id = "bgTop",
        px = "0.5",
        py = "0.025+10",
        sw = "1",
        sh = "0.05+20",
        color = "#0a0a0a",
        children = {
            {
                type = "Button",
                id = "btnWorkspace",
                px = "h*1",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/folder.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnFileOpen",
                px = "h*2",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/file_open.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnFileCreate",
                px = "h*3",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/file_create.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnFileSave",
                px = "h*4",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/file_save.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnPreview",
                px = "h*5",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/preview.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnBuild",
                px = "h*6",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/play.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnCode",
                px = "h*7",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/code.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnExplorer",
                px = "h*8",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/explorer.png",
                children = {},
            },
            {
                type = "Text",
                id = "txtTitle",
                px = "1-150",
                py = "0.5",
                sw = "0",
                sh = "0",
                text = "Title",
                children = {},
            },
            {
                type = "Button",
                id = "btnGithub",
                px = "1-100",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/github.png",
                children = {},
            },
            {
                type = "Button",
                id = "btnClose",
                px = "1-50",
                py = "0.5",
                sw = "h*0.5",
                sh = "0.5",
                icon = "media/exit.png",
                children = {},
            },
        },
    },
    {
        type = "Rectangle",
        id = "nodeStage",
        px = "0.5",
        py = "0.475+10",
        sw = "0.8-200",
        sh = "0.85-20",
        color = "#2c2c2c",
        children = {},
    },
    {
        type = "Rectangle",
        id = "bgLeft",
        px = "0.05+50",
        py = "0.525+10",
        sw = "0.1+100",
        sh = "0.95-20",
        color = "#1e1e1e",
        children = {
            {
                type = "Rectangle",
                id = "boxTree",
                px = "0.5",
                py = "0.5+15",
                sw = "0.9",
                sh = "1-30",
                color = "#0a0a0a",
                children = {
                    {
                        type = "Text",
                        id = "textTree",
                        px = "0.5",
                        py = "0-15",
                        sw = "0",
                        sh = "0+25",
                        text = "Tree",
                        children = {},
                    },
                    {
                        type = "Button",
                        id = "btnUp",
                        px = "0.1",
                        py = "0.025+10",
                        sw = 15,
                        sh = 15,
                        icon = "media/angle_up.png",
                        children = {},
                    },
                    {
                        type = "Template",
                        id = "templateUi",
                        px = "0.5",
                        py = "0.025+10",
                        sw = "0.65",
                        sh = "0.05",
                        path = "./editor/ui/editor_leaf.ui.lua",
                        children = {},
                    },
                    {
                        type = "Button",
                        id = "btnDown",
                        px = "0.9",
                        py = "0.025+10",
                        sw = 15,
                        sh = 15,
                        icon = "media/angle_down.png",
                        children = {},
                    },
                    {
                        type = "Rectangle",
                        id = "bgTree",
                        px = "0.5",
                        py = "0.525+5",
                        sw = "0.9",
                        sh = "0.9",
                        color = "#1e1e1e",
                        children = {
                            {
                                type = "Clipper",
                                id = "clipperTree",
                                px = "0.5",
                                py = "0.5",
                                sw = "1",
                                sh = "1",
                                children = {},
                            },
                        },
                    },
                },
            },
        },
    },
    {
        type = "Rectangle",
        id = "bgRight",
        px = "0.95-50",
        py = "0.525+10",
        sw = "0.1+100",
        sh = "0.95-20",
        color = "#1e1e1e",
        children = {
            {
                type = "Rectangle",
                id = "boxAttribute",
                px = "0.5",
                py = "0.5+15",
                sw = "0.9",
                sh = "1-30",
                color = "#0a0a0a",
                children = {
                    {
                        type = "Text",
                        id = "textAttribute",
                        px = "0.5",
                        py = "0-15",
                        sw = "0",
                        sh = "0+25",
                        text = "Attribute",
                        children = {},
                    },
                    {
                        type = "Button",
                        id = "btnUp",
                        px = "0.1",
                        py = "0.025+10",
                        sw = "0+15",
                        sh = "0+15",
                        icon = "media/angle_up.png",
                        children = {},
                    },
                    {
                        type = "Template",
                        id = "templateCtrl",
                        px = "0.325",
                        py = "0.025+10",
                        sw = "0.3",
                        sh = "0.05",
                        path = "./editor/ui/editor_attr.ui.lua",
                        children = {},
                    },
                    {
                        type = "Template",
                        id = "templateProp",
                        px = "0.675",
                        py = "0.025+10",
                        sw = "0.3",
                        sh = "0.05",
                        path = "./editor/ui/editor_attr.ui.lua",
                        children = {},
                    },
                    {
                        type = "Button",
                        id = "btnDown",
                        px = "0.9",
                        py = "0.025+10",
                        sw = 15,
                        sh = 15,
                        icon = "media/angle_down.png",
                        children = {},
                    },
                    {
                        type = "Rectangle",
                        id = "bgAttribute",
                        px = "0.5",
                        py = "0.525+5",
                        sw = "0.9",
                        sh = "0.9",
                        color = "#1e1e1e",
                        children = {
                            {
                                type = "Clipper",
                                id = "clipperAttribute",
                                px = "0.5",
                                py = "0.5",
                                sw = "1",
                                sh = "1",
                                children = {},
                            },
                        },
                    },
                },
            },
        },
    },
    {
        type = "Rectangle",
        id = "bgBottom",
        px = "0.5",
        py = "0.95",
        sw = "0.8-200",
        sh = "0.1",
        color = "#0a0a0a",
        children = {},
    },
}