{
    {
        type = "Rectangle",
        id = "bg",
		x = '0.5',
		y = '0.5',
		w = '1',
		h = '1',
		color = "#101010aa",
	},
    {
        type = "Rectangle",
        id = "line",
		x = '0.5',
		y = '0.5',
		w = '1',
		h = '1',
        mode = 'line',
		color = "#ffffffaa",
	},
    {
        type = "Text",
        id = "text",
        x = '0.5-12',
        y = '0.5',
        w = 0,
        h = 0,
        text = "[...]",
    },
    {
        type = "Button",
        id = "btnEdit",
        x = '1-15',
        y = '0.5',
        w = 15,
        h = 15,
        icon = "/media/edit.png",
    },
}