{
    {
        type = "Rectangle",
        id = "bg",
		x = '0.5',
		y = '0.5',
		w = '1',
		h = '1',
		bg = "#101010aa",
	},
    {
        type = "Rectangle",
        id = "line",
		x = '0.5',
		y = '0.5',
		w = '1',
		h = '1',
        mode = 'line',
		bg = "#ffffff55",
	},
    {
        type = "Text",
        id = "text",
        x = '0.5',
        y = '0.5',
        w = '0',
        h = '0',
        text = "[...]",
    },
    {
        type = "Button",
        id = "btnSelect",
        x = '0.5',
        y = '0.5',
        w = '1',
        h = '1',
        bg = "#00000000",
    },
    {
        type = "Button",
        id = "btnFold",
        x = '0+15',
        y = '0.5',
        w = 15,
        h = 15,
        icon = "media/up.png",
    },
    {
        type = "Button",
        id = "btnEdit",
        x = '1-15',
        y = '0.5',
        w = 15,
        h = 15,
        icon = "media/edit.png",
    },
}