{
    {
        type = "Rectangle",
        id = "bgTop",
        x = '0.5',
        y = '0.05',
        w = "1",
        h = "0.1",
        color = {10, 10, 10},
        children = {
            {
                type = "Button",
                id = "btnNode",
                x = 50,
                y = '0.5',
                w = 25,
                h = 25,
            },
            {
                type = "Button",
                id = "btnTree",
                x = 100,
                y = '0.5',
                w = 25,
                h = 25,
            },
            {
                type = "Text",
                id = "txtTitle",
                x = '0.5',
                y = '0.5',
                w = 0,
                h = 0,
                text = "Title",
            },
            {
                type = "Button",
                id = "btnClose",
                x = "1-25",
                y = '0.5',
                w = 25,
                h = 25,
            },
        },
    },
    {
        type = "Rectangle",
        id = "bgStage",
        x = '0.5',
        y = '0.5',
        w = "0.6",
        h = "0.8",
        color = {44, 44, 44},
    },
    {
        type = "Rectangle",
        id = "bgLeft",
        x = '0.1',
        y = '0.55',
        w = "0.2",
        h = "0.9",
        color = {30, 30, 30, 255},
        children = {
            {
                type = "Text",
                id = "textTree",
                x = "0.5",
                y = '0+15',
                w = 0,
                h = 25,
                text = "Tree"
            },
            {
                type = "Rectangle",
                id = "boxTree",
                x = '0.5',
                y = '0.5+15',
                w = "0.9",
                h = "1-30",
                color = {10, 10, 10},
            },
        },
    },
    {
        type = "Rectangle",
        id = "bgRight",
        x = '0.9',
        y = '0.55',
        w = "0.2",
        h = "0.9",
        color = {30, 30, 30, 255},
        children = {
            {
                type = "Text",
                id = "textProp",
                x = "0.5",
                y = '0+15',
                w = 0,
                h = 25,
                text = "Prop"
            },
            {
                type = "Rectangle",
                id = "boxProp",
                x = '0.5',
                y = '0.5+15',
                w = "0.9",
                h = "1-30",
                color = {10, 10, 10},
            },
        },
    },
    {
        type = "Rectangle",
        id = "bgBottom",
        x = '0.5',
        y = '0.95',
        w = "0.6",
        h = "0.1",
        color = {10, 10, 10},
    },
}