{
    window = {
        type = "Window",
        id = "rootWindow",
        x = 100,
        y = 100,
        w = 500,
        h = 500,
    },
    options = {
        background = {75, 75, 75},
        fullscreen = false,
        title = "Editor!",
    },
    children = {
        {
            type = "Rectangle",
            id = "bgTop",
            x = '0.5',
            y = '0.05',
            w = "1",
            h = "0.1",
            color = {10, 10, 10},
        },
        {
            type = "Rectangle",
            id = "bgStage",
            x = 250,
            y = 250,
            w = "0.6",
            h = "0.6",
            color = {77, 77, 77},
        },
        {
            type = "Rectangle",
            id = "bgLeft",
            x = '0.1',
            y = '0.55',
            w = "0.2",
            h = "0.9",
            color = {30, 30, 30},
            children = {
                {
                    type = "Button",
                    id = "btnNode",
                    x = "0.25",
                    y = '0+15',
                    w = '0.4',
                    h = 25,
                },
                {
                    type = "Button",
                    id = "btnTree",
                    x = "0.75",
                    y = '0+15',
                    w = '0.4',
                    h = 25,
                },
                {
                    type = "Rectangle",
                    id = "boxNode",
                    x = '0.5',
                    y = '0.5+15',
                    w = "0.9",
                    h = "1-30",
                    color = {10, 10, 10},
                },
            },
        },
        {
            type = "Rectangle",
            id = "bgRight",
            x = '0.9',
            y = '0.55',
            w = "0.2",
            h = "0.9",
            color = {30, 30, 30},
            children = {
                {
                    type = "Text",
                    id = "textProp",
                    x = "0.5",
                    y = '0+15',
                    w = 0,
                    h = 25,
                    text = "Prop"
                },
                {
                    type = "Rectangle",
                    id = "boxProp",
                    x = '0.5',
                    y = '0.5+15',
                    w = "0.9",
                    h = "1-30",
                    color = {10, 10, 10},
                },
            },
        },
        {
            type = "Rectangle",
            id = "bgBottom",
            x = '0.5',
            y = '0.95',
            w = "0.6",
            h = "0.1",
            color = {10, 10, 10},
        },
        {
            type = "Button",
            id = "btnClose",
            x = "1-25",
            y = 25,
            w = 25,
            h = 25,
        },
        {
            type = "Text",
            id = "txtTitle",
            x = '0.1',
            y = 25,
            w = 0,
            h = 0,
            text = "Title",
        },
    }
}